### ISSUE TITLE
Error response from daemon: No such image: registry.gitlab.com/mlpds_mit/askcos/askcos-vue-nginx:dev

### ISSUE THREAD

**Issue by pablo-01** [FourThievesVinegar/askcos2_core#1]
Hi,

I'm trying to do local deployment but getting an error: `Error response from daemon: No such image: registry.gitlab.com/mlpds_mit/askcos/askcos-vue-nginx:dev`. 

Full log attached. 
[log.txt](https://github.com/user-attachments/files/17006934/log.txt)

**Comment by youhavethewrong** [comment]
I noticed this too. I believe it has to do with [this line](https://github.com/FourThievesVinegar/askcos2_core/blob/main/scripts/pre_deploy.py#L223). To work around, I just changed line 223 to be `output_dir = repo.split("FourThievesVinegar/")[-1][:-4]` and was able to proceed.
